# Generated by Django 2.0.7 on 2018-12-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20181120_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='hidden',
            field=models.SmallIntegerField(default=0, verbose_name='Скрытый?(0-нет, 1-да)'),
        ),
    ]
