# Generated by Django 2.0.7 on 2018-12-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_topic_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров темы'),
        ),
    ]
